// Base service descriptions used by catalog.js.
export const domains = [
  { id: 'identity', name: 'Identity & access', short: 'Identity', icon: 'fingerprint', color: '#d1b6ff', position: [265, 170], description: 'Who can act, what they can reach, and where trust begins.', lens: 'Follow the principal, its session, and the policies that shape its access.', services: ['iam', 'sts', 'identity-center', 'kms'] },
  { id: 'compute', name: 'Compute', short: 'Compute', icon: 'chip', color: '#ffc58f', position: [745, 152], description: 'The workloads that turn permissions into real activity.', lens: 'Connect workload identity with process, runtime, and network evidence.', services: ['ec2', 'lambda', 'ecs', 'eks'] },
  { id: 'data', name: 'Data & storage', short: 'Data', icon: 'database', color: '#b7dca6', position: [862, 395], description: 'Where information lives, moves, and needs protecting.', lens: 'Separate the ability to access data from evidence that access actually occurred.', services: ['s3', 'rds', 'dynamodb', 'backup'] },
  { id: 'network', name: 'Network & edge', short: 'Network', icon: 'network', color: '#9acbe6', position: [563, 570], description: 'The paths between a request and your cloud resources.', lens: 'Follow ingress, routing, and egress without assuming a network boundary is an identity boundary.', services: ['vpc', 'route53', 'cloudfront', 'waf'] },
  { id: 'detection', name: 'Detection & response', short: 'Detection', icon: 'radar', color: '#e6df9c', position: [220, 455], description: 'The signals that make cloud activity understandable.', lens: 'Turn an alert into a testable hypothesis, an evidence trail, and a response decision.', services: ['guardduty', 'cloudtrail', 'securityhub', 'cloudwatch'] },
  { id: 'delivery', name: 'Delivery & secrets', short: 'Delivery', icon: 'layers', color: '#e8acd1', position: [505, 65], description: 'How changes and credentials arrive in your environment.', lens: 'Trace a production change back to its artifact, approval, and deployment identity.', services: ['codepipeline', 'cloudformation', 'ecr', 'secretsmanager'] },
];

const service = (id, name, label, icon, summary, question, guardrail, doc, related) => ({ id, name, label, icon, summary, question, guardrail, doc, related });
export const services = [
  service('iam', 'AWS IAM', 'Permissions & trust', 'fingerprint', 'IAM defines who can access AWS resources and which actions are allowed. Read the principal, policy, and resource together.', 'Which principal acted, through which session, and under which effective permissions?', 'Review least privilege and trust policies. Account for explicit denies and organization controls.', 'IAM/latest/UserGuide/introduction.html', ['sts', 'cloudtrail', 's3']),
  service('sts', 'AWS STS', 'Temporary credentials', 'key', 'Security Token Service issues temporary credentials. A role session carries an identity context that matters during an investigation.', 'Who created this session, when was it issued, and which role did it assume?', 'Constrain role trust and session duration. Consider existing sessions when containing access.', 'STS/latest/APIReference/welcome.html', ['iam', 'cloudtrail', 'ec2']),
  service('identity-center', 'IAM Identity Center', 'Workforce access', 'users', 'Centralize workforce access to AWS accounts and applications through permission sets and an identity source.', 'Can the account activity be tied back to a workforce sign-in and assigned permission set?', 'Use strong authentication and regularly review account assignments.', 'singlesignon/latest/userguide/what-is.html', ['iam', 'sts', 'cloudtrail']),
  service('kms', 'AWS KMS', 'Encryption keys', 'key', 'KMS manages cryptographic keys and authorizes their use. Encryption protection depends on key access as well as storage access.', 'Which principal used the key, for which operation, and with what encryption context?', 'Separate key administration from key usage and review key policies.', 'kms/latest/developerguide/overview.html', ['s3', 'cloudtrail', 'iam']),
  service('ec2', 'Amazon EC2', 'Virtual machines', 'chip', 'EC2 provides virtual compute inside a network environment. Instance roles, storage, and runtime state provide different parts of an incident story.', 'What changed on the instance, and does network or identity evidence agree with the host evidence?', 'Prepare evidence collection and workload-aware containment before an incident.', 'AWSEC2/latest/UserGuide/concepts.html', ['vpc', 'iam', 'guardduty']),
  service('lambda', 'AWS Lambda', 'Event-driven compute', 'bolt', 'Lambda runs functions in response to events. Execution roles, triggers, code versions, and logs help explain its behavior.', 'Was the activity caused by an expected trigger and deployed function version?', 'Scope execution permissions and control who can change code, layers, or triggers.', 'lambda/latest/dg/welcome.html', ['iam', 'cloudwatch', 's3']),
  service('ecs', 'Amazon ECS', 'Container workloads', 'box', 'ECS orchestrates container tasks. Task identity, the container image, and deployment settings are useful investigation anchors.', 'Which task revision and image digest were running when the finding occurred?', 'Distinguish task roles from execution roles and use controlled image sources.', 'AmazonECS/latest/developerguide/Welcome.html', ['ecr', 'iam', 'vpc']),
  service('eks', 'Amazon EKS', 'Kubernetes', 'hexagon', 'EKS provides managed Kubernetes. Kubernetes permissions and AWS permissions form separate, connected access paths.', 'Does the activity originate from Kubernetes access, a workload identity, or the AWS control plane?', 'Review both Kubernetes RBAC and AWS access, and prepare appropriate control-plane logs.', 'eks/latest/userguide/what-is-eks.html', ['iam', 'ecr', 'vpc']),
  service('s3', 'Amazon S3', 'Object storage', 'database', 'S3 stores objects behind access controls. A policy change describes exposure; object-level evidence describes use.', 'Was public access actually effective, and are object data events available for the period?', 'Use Block Public Access where appropriate and deliberately configure object-level logging.', 'AmazonS3/latest/userguide/Welcome.html', ['iam', 'kms', 'cloudtrail']),
  service('rds', 'Amazon RDS', 'Relational databases', 'database', 'RDS hosts managed relational databases. Network access, database authentication, and engine logs answer different questions.', 'Which database identity connected, and which engine audit records can show its actions?', 'Limit connectivity, protect credentials, and configure engine-appropriate audit logging.', 'AmazonRDS/latest/UserGuide/Welcome.html', ['vpc', 'kms', 'secretsmanager']),
  service('dynamodb', 'Amazon DynamoDB', 'Key-value data', 'database', 'DynamoDB provides managed key-value and document storage. Separate table configuration changes from item-level operations.', 'Which identity accessed the table, and is the required data-event coverage enabled?', 'Scope permissions to required tables and actions; plan recovery for important data.', 'amazondynamodb/latest/developerguide/Introduction.html', ['iam', 'kms', 'cloudtrail']),
  service('backup', 'AWS Backup', 'Recovery & resilience', 'archive', 'AWS Backup coordinates protection and recovery for supported resources. A backup is useful only when recovery is understood and tested.', 'Is there an appropriate recovery point, and has the restore path been validated?', 'Separate recovery permissions and test restoration against workload requirements.', 'aws-backup/latest/devguide/whatisbackup.html', ['iam', 'kms', 'cloudtrail']),
  service('vpc', 'Amazon VPC', 'Network boundaries', 'network', 'VPC provides logically isolated networks. Routes, security groups, endpoints, and flow logs describe different aspects of connectivity.', 'Which path was available, and what do recorded network flows actually establish?', 'Review ingress and egress separately. Flow logs provide metadata, not packet contents.', 'vpc/latest/userguide/what-is-amazon-vpc.html', ['ec2', 'rds', 'cloudwatch']),
  service('route53', 'Amazon Route 53', 'DNS & routing', 'globe', 'Route 53 provides DNS and routing capabilities. DNS changes and resolver observations can connect an application to a destination.', 'Was a DNS configuration changed, or did a workload start resolving an unusual domain?', 'Protect DNS administration and enable relevant query logging for your architecture.', 'Route53/latest/DeveloperGuide/Welcome.html', ['vpc', 'cloudfront', 'cloudtrail']),
  service('cloudfront', 'Amazon CloudFront', 'Content delivery', 'globe', 'CloudFront distributes content through edge locations. Requests, cache behavior, and origin access need to be understood together.', 'Did the request reach the origin, and which distribution behavior handled it?', 'Protect origin access and configure the request logs needed for investigation.', 'AmazonCloudFront/latest/DeveloperGuide/Introduction.html', ['waf', 's3', 'cloudwatch']),
  service('waf', 'AWS WAF', 'Request filtering', 'shield', 'WAF inspects supported web traffic using configured rules. A blocked request shows a rule decision, not necessarily an application compromise.', 'Which rule matched, what action ran, and what does application evidence show?', 'Tune rules against representative traffic and preserve useful request evidence.', 'waf/latest/developerguide/what-is-aws-waf.html', ['cloudfront', 'cloudwatch', 's3']),
  service('guardduty', 'Amazon GuardDuty', 'Threat findings', 'radar', 'GuardDuty surfaces suspicious activity from supported data sources. A finding starts an investigation; context determines the response.', 'Does the finding match expected activity, and which independent evidence supports the hypothesis?', 'Review enabled protection coverage and validate how findings reach responders.', 'guardduty/latest/ug/what-is-guardduty.html', ['cloudtrail', 'securityhub', 'ec2']),
  service('cloudtrail', 'AWS CloudTrail', 'API activity', 'activity', 'CloudTrail records supported account activity. Event fields help reconstruct the actor, action, resource, and timing.', 'Which event fields identify the caller and request, and are the needed event categories recorded?', 'Protect trail delivery and review management, data, and network-event coverage separately.', 'awscloudtrail/latest/userguide/cloudtrail-user-guide.html', ['iam', 's3', 'cloudwatch']),
  service('securityhub', 'AWS Security Hub', 'Security findings', 'shield', 'Security Hub helps bring security findings into a common workflow. Preserve the original finding context when prioritizing response.', 'Are related findings describing the same resource or incident, and who owns the response?', 'Define routing, ownership, and escalation; verify integration and regional coverage.', 'securityhub/latest/userguide/what-is-securityhub.html', ['guardduty', 'cloudwatch', 'iam']),
  service('cloudwatch', 'Amazon CloudWatch', 'Logs & monitoring', 'activity', 'CloudWatch gathers operational signals through logs, metrics, and alarms. These observations help validate both impact and recovery.', 'Did workload behavior change at the same time as the security signal?', 'Set useful retention, protect log access, and test actionable alarms.', 'AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html', ['lambda', 'ec2', 'cloudtrail']),
  service('codepipeline', 'AWS CodePipeline', 'Release workflows', 'layers', 'CodePipeline coordinates release stages. Source revisions, approvals, and deployment identities connect code changes to production.', 'Which artifact was promoted, who approved it, and which identity deployed it?', 'Protect source and artifact access, and scope deployment roles to their environment.', 'codepipeline/latest/userguide/welcome.html', ['iam', 'ecr', 'cloudformation']),
  service('cloudformation', 'AWS CloudFormation', 'Infrastructure as code', 'layers', 'CloudFormation describes and provisions resources through stacks. Templates, change sets, and stack events explain intended changes.', 'Does the resource change match an authorized stack operation and reviewed template?', 'Review change sets and limit the permissions of provisioning roles.', 'AWSCloudFormation/latest/UserGuide/Welcome.html', ['iam', 'cloudtrail', 's3']),
  service('ecr', 'Amazon ECR', 'Container registry', 'box', 'ECR stores container images. Image digests and repository activity help connect a workload to the artifact that created it.', 'Which exact digest ran, and how did that image enter the repository?', 'Control image publication and review scanning results before deployment.', 'AmazonECR/latest/userguide/what-is-ecr.html', ['ecs', 'eks', 'iam']),
  service('secretsmanager', 'AWS Secrets Manager', 'Secret lifecycle', 'key', 'Secrets Manager stores and manages secrets used by applications. Secret access and credential use are related but distinct events.', 'Who retrieved the secret, and what evidence shows how the underlying credential was used?', 'Scope retrieval permissions and plan rotation with the consuming application owner.', 'secretsmanager/latest/userguide/intro.html', ['kms', 'iam', 'cloudtrail']),
];
export const getDomain = id => domains.find(d => d.id === id);
export const getService = id => services.find(s => s.id === id);
export const domainOf = id => domains.find(d => d.services.includes(id));

export const stories = [
  { id: 'identity-signal', title: 'A familiar identity. An unfamiliar pattern.', short: 'Follow an identity signal', category: 'Identity investigation', domain: 'identity', service: 'iam', color: '#d1b6ff', icon: 'fingerprint', subtitle: 'Follow a suspicious session from a GuardDuty finding to a scoped response.', nodes: ['guardduty', 'sts', 'cloudtrail', 's3'],
    steps: [
      { name: 'Detect', title: 'An anomaly is a starting point.', text: 'A synthetic GuardDuty finding flags unusual API behavior for an assumed role. Record the finding context before deciding whether the activity is unauthorized.', question: 'Could an approved automation change explain this?', focus: 'guardduty', event: { source: 'Synthetic finding summary', findingType: 'Discovery:IAMUser/AnomalousBehavior', principal: 'training-reporting-role', region: 'ap-southeast-2', status: 'Needs validation' }, takeaway: 'Severity sets urgency. Corroborating evidence sets confidence.' },
      { name: 'Investigate', title: 'Reconstruct the session.', text: 'Compare the role session, source, and timing with expected automation. Correlate recorded API activity. Object access requires the relevant S3 data-event coverage.', question: 'What was observed, and what remains unrecorded?', focus: 'cloudtrail', event: { source: 'Synthetic CloudTrail excerpt', eventTime: '2026-09-01T02:14:00Z', eventSource: 's3.amazonaws.com', eventName: 'GetObject', awsRegion: 'ap-southeast-2', sourceIPAddress: '192.0.2.24', userIdentity: { type: 'AssumedRole', arn: 'arn:aws:sts::123456789012:assumed-role/training-reporting-role/demo-session' }, requestParameters: { bucketName: 'example-training-reports', key: 'synthetic-report.csv' } }, takeaway: 'An observed request is evidence. Data loss still needs a scoped assessment.' },
      { name: 'Contain', title: 'Interrupt access with context.', text: 'If unauthorized use is corroborated, coordinate containment with the workload owner. Address the originating credential and existing role sessions, while preserving evidence.', question: 'What legitimate workload depends on this identity?', focus: 'sts', event: { source: 'Simulated response decision', approval: 'Workload owner required', scope: 'Affected identity and active sessions', evidence: 'Preserve finding and event exports', impact: 'Reporting jobs may pause', actionStatus: 'Illustrative only — no AWS action' }, takeaway: 'A containment decision includes scope, customer impact, and a recovery owner.' },
      { name: 'Recover', title: 'Prove the response worked.', text: 'Restore the authorized access path, validate expected jobs, and review fresh activity. Record any telemetry gaps and assign follow-up changes to owners.', question: 'What evidence would make us reopen the incident?', focus: 's3', event: { source: 'Synthetic recovery checklist', access: 'Approved workload path validated', monitoring: 'Watch for recurrence', followUp: 'Review trust and session controls', handoff: 'Document timeline, uncertainty, and owners' }, takeaway: 'Recovery is an observed outcome, not just a completed change.' },
    ], sourceLinks: [['GuardDuty IAM findings', 'https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_finding-types-iam.html'], ['CloudTrail event fields', 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html'], ['AWS containment guidance', 'https://docs.aws.amazon.com/security-ir/latest/userguide/contain.html']] },
  { id: 'storage-exposure', title: 'An open policy. An unanswered question.', short: 'Assess a storage exposure', category: 'Data exposure assessment', domain: 'data', service: 's3', color: '#b7dca6', icon: 'database', subtitle: 'Separate a policy finding from effective exposure and confirmed object access.', nodes: ['s3', 'iam', 'cloudtrail', 'kms'],
    steps: [
      { name: 'Detect', title: 'Find the effective exposure.', text: 'A synthetic configuration review identifies a broad bucket policy. Check Block Public Access and other applicable controls before declaring the bucket publicly accessible.', question: 'Did the policy actually make access possible?', focus: 's3', event: { source: 'Synthetic configuration review', resource: 'example-training-reports', signal: 'Broad bucket policy detected', effectiveExposure: 'Pending review' }, takeaway: 'A risky policy and an effective access path are different findings.' },
      { name: 'Investigate', title: 'Establish the exposure window.', text: 'Review the policy change time and available object-level logs. Check data sensitivity with the owner and explicitly document any period without access telemetry.', question: 'Can the available records support or rule out access?', focus: 'cloudtrail', event: { source: 'Synthetic assessment note', policyChangedAt: '2026-09-01T02:10:00Z', dataEventCoverage: 'Not enabled during the example window', conclusion: 'Object access cannot be determined from these records' }, takeaway: 'Missing access logs are an uncertainty, not proof that no access occurred.' },
      { name: 'Contain', title: 'Close the unintended path.', text: 'Coordinate with the application owner to remove unintended access. Evaluate Block Public Access against the workload design and preserve the previous configuration for the incident record.', question: 'Does any approved public workflow rely on this path?', focus: 'iam', event: { source: 'Simulated response decision', proposedChange: 'Remove unintended public access', dependency: 'Confirm intended website or sharing behavior', actionStatus: 'Illustrative only — no AWS action' }, takeaway: 'Protect the data while accounting for legitimate application behavior.' },
      { name: 'Recover', title: 'Validate access from both sides.', text: 'Confirm authorized application access works and unintended access is blocked. Document the exposure assessment, evidence limitations, and planned monitoring.', question: 'Have we verified both the permitted and denied paths?', focus: 's3', event: { source: 'Synthetic recovery checklist', authorizedPath: 'Validate with owner', unintendedPath: 'Verify denied access', followUp: 'Configure appropriate data-event coverage' }, takeaway: 'Access controls and observable access need separate validation.' },
    ], sourceLinks: [['S3 Block Public Access', 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html'], ['CloudTrail event fields', 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html']] },
  { id: 'logging-gap', title: 'When the trail goes quiet.', short: 'Investigate a logging gap', category: 'Detection resilience', domain: 'detection', service: 'cloudtrail', color: '#e6df9c', icon: 'activity', subtitle: 'Investigate a logging change and restore confidence in your evidence sources.', nodes: ['cloudtrail', 'iam', 's3', 'cloudwatch'],
    steps: [
      { name: 'Detect', title: 'Treat silence as a question.', text: 'A synthetic alert reports a trail logging change. Check service health, delivery status, and authorized changes before assigning intent.', question: 'Is this a configuration change, a delivery problem, or expected maintenance?', focus: 'cloudtrail', event: { source: 'Synthetic CloudTrail excerpt', eventTime: '2026-09-01T02:14:00Z', eventSource: 'cloudtrail.amazonaws.com', eventName: 'StopLogging', awsRegion: 'ap-southeast-2', sourceIPAddress: '192.0.2.24' }, takeaway: 'A logging interruption deserves investigation even before intent is known.' },
      { name: 'Investigate', title: 'Scope the missing view.', text: 'Identify the actor, affected trail, regions, and event categories. Check independent evidence sources and define the suspected gap in the incident timeline.', question: 'Which observations are still available elsewhere?', focus: 'iam', event: { source: 'Synthetic evidence assessment', affectedTrail: 'training-account-trail', actor: 'Pending validation', remainingSources: ['CloudWatch workload logs', 'Available event history'], limitation: 'Coverage differs by source and event category' }, takeaway: 'Alternative logs can add context without replacing every missing event.' },
      { name: 'Contain', title: 'Restore and protect collection.', text: 'Coordinate restoration of the intended logging configuration. If the change was unauthorized, contain the responsible access path and preserve the existing records.', question: 'Can the same identity interrupt logging again?', focus: 's3', event: { source: 'Simulated response decision', proposedChange: 'Restore intended trail configuration', protection: 'Review trail and log-storage permissions', actionStatus: 'Illustrative only — no AWS action' }, takeaway: 'Restoring logging and addressing its interruption are separate tasks.' },
      { name: 'Recover', title: 'Verify delivery, not just settings.', text: 'Confirm fresh expected events reach the intended destination. Record the remaining visibility gap and validate the alerting path for future interruptions.', question: 'Can the responder find a fresh, expected event?', focus: 'cloudwatch', event: { source: 'Synthetic recovery checklist', delivery: 'Validate a fresh event', notification: 'Exercise the alert route', residualRisk: 'Document historical visibility gap' }, takeaway: 'A healthy configuration should produce observable evidence.' },
    ], sourceLinks: [['CloudTrail documentation', 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html'], ['GuardDuty IAM findings', 'https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_finding-types-iam.html']] },
];
