// Claim-specific AWS sources, reviewed 2026-09-24. This is reference data, not observed account state.
export const evidenceReviewDate='2026-09-24';
export const evidenceGuides=[
  {id:'management-history',title:'CloudTrail event history',category:'Identity & API activity',services:['cloudtrail','iam','sts'],availability:'90-day regional history',
    describes:'Recent management API activity, including identity context and event details.',
    prerequisite:'Select the relevant Region and time range. Preserve a trail or event data store for an ongoing record beyond event history.',
    limitation:'Event history excludes data events. An empty search does not establish that no object access or invocation occurred.',
    checks:['Confirm the Region and time window.','Review the default read-only filter before drawing conclusions.'],
    source:'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/view-cloudtrail-events-console.html'},
  {id:'data-events',title:'CloudTrail data events',category:'Resource operations',services:['cloudtrail','s3','lambda','sns'],availability:'Explicit collection required',
    describes:'Selected resource operations such as S3 object access, Lambda invocation, and SNS publishing.',
    prerequisite:'Configure data event collection and selectors for the resource types and operations under review.',
    limitation:'Trails and event data stores do not collect data events by default. Selector scope determines which operations are retained.',
    checks:['Check read/write selection and the selected resource scope.','Verify the collection was enabled during the investigation window.'],
    source:'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html'},
  {id:'network-flows',title:'VPC Flow Logs',category:'Network activity',services:['vpc','ec2'],availability:'Collection has exclusions',
    describes:'Records of selected network-interface traffic; useful context for network investigations.',
    prerequisite:'Confirm the flow-log resource, destination, record format, and whether traffic existed in the selected window.',
    limitation:'Not every type of IP traffic is recorded. Flow records can also be skipped; a missing record is not proof of no traffic.',
    checks:['Review the documented traffic exclusions.','Check delivery and log-status before interpreting gaps.'],
    source:'https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-limitations.html'},
  {id:'eks-audit',title:'EKS control-plane logs',category:'Kubernetes activity',services:['eks','cloudwatch'],availability:'Disabled by default',
    describes:'Cluster API, audit, authenticator, controller-manager, and scheduler logs, selected per cluster.',
    prerequisite:'Enable the required log types for the cluster and inspect their CloudWatch log streams.',
    limitation:'Control-plane logging is not sent to CloudWatch by default. Delivery is best effort; enabling one type does not enable the others.',
    checks:['Verify audit and authenticator settings separately.','Match the cluster, account, and time window.'],
    source:'https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html'},
  {id:'lambda-logs',title:'Lambda application logs',category:'Workload execution',services:['lambda','cloudwatch'],availability:'Execution-role dependent',
    describes:'Function invocation logs and application-generated logging statements sent to CloudWatch Logs.',
    prerequisite:'The execution role needs CloudWatch Logs permissions; confirm the configured destination log group.',
    limitation:'Delivery depends on role permissions and can take several minutes. Application detail also depends on what the function logs.',
    checks:['Check log-group and stream permissions for the execution role.','Inspect the configured destination, including custom log groups.'],
    source:'https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html'},
  {id:'s3-access',title:'S3 server access logs',category:'Storage requests',services:['s3'],availability:'Best-effort delivery',
    describes:'Request-level records for a bucket with server access logging configured.',
    prerequisite:'Verify logging and the destination used for the bucket under investigation.',
    limitation:'Delivery can be delayed, duplicated, or absent. AWS does not guarantee a complete accounting of every request.',
    checks:['Account for delivery delay when choosing the review window.','Corroborate requests with separately configured evidence sources.'],
    source:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html'},
];
export const evidenceForService=id=>evidenceGuides.filter(guide=>guide.services.includes(id));
